include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "build/**"
    - "assets/**"
    - "**.g.dart"
    - "**.chopper.dart"
    - "**.config.dart"
    - "**.freezed.dart"
    - "**.mocks.dart"

linter:
  rules:
    # No need for this in app-type project
    public_member_api_docs: false
    # 120 characters per line
    lines_longer_than_80_chars: false
