name: tiny_hn
version: 1.0.0+1
publish_to: none
description: Tiny hackernews client app made with Flutter
environment: 
  sdk: '>=3.1.2 <4.0.0'
  flutter: 3.13.4

dependencies: 
  chopper: 7.0.6
  collection: 1.17.2
  easy_localization: 3.0.3
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_hooks: 0.20.1
  flutter_svg: 2.0.7
  freezed_annotation: 2.4.1
  get_it: 7.6.4
  go_router: 10.2.0
  google_fonts: 6.1.0
  hooked_bloc: 1.4.3
  injectable: 2.3.0
  json_annotation: 4.8.1
  rxdart: 0.27.7

dev_dependencies: 
  bloc_test: 9.1.4
  build_runner: 2.4.6
  chopper_generator: 7.0.4
  flutter_lints: 2.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.4.1
  go_router_builder: 2.3.3
  injectable_generator: 2.4.0
  json_serializable: 6.7.1
  mockito: 5.4.2
  pubspec_dependency_sorter: 1.0.4
  very_good_analysis: ^5.1.0

flutter: 
  assets: 
    - assets/translations/
  uses-material-design: true
